# Site settings
title: Rethinking Bayes
description: "Exercise solutions in Python for the book Statistical Rethinking: A Bayesian Course with Examples in R and Stan, by Richard McElreath"
baseurl: "/RethinkingBayes"
url: "https://philipgriffith.github.io"

# Author
author:
  name: Philip Griffith
  url: https://github.com/PhilipGriffith
  email: philip.griffith@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages
destination: ../Site/
keep_files:
  - .git

# Assets
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  collection: malkuth
  sort_field: title

collections:
  malkuth:
    output: true
    permalink: '/malkuth/:name'
  sephiroth:
    output: true
    permalink: '/sephiroth/:name'    

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - Notebooks
  - assets/images/optipng.exe
  - assets/images/optimize.bat